### ISSUE TITLE
cmdline.py doesnt work with --fasthenry option

### ISSUE THREAD

**Issue by twitchyliquid64** [ignamv/kicad_scripts#2]
```
xxx@xxx-TECRA-M11:~/PCBs/kicad_scripts-master/rfid_calculator$ python3 cmdline.py --width 50 --height 50 --trace_width 1 --turns 3 --kicad_mod=test.kicad_mod --fasthenry --frequency=125000 --mm --pitch 2
Traceback (most recent call last):
  File "cmdline.py", line 110, in <module>
    trace_width, trace_height, args.frequency)
  File "/home/xxx/PCBs/kicad_scripts-master/rfid_calculator/fasthenry.py", line 66, in coil_impedance
    universal_newlines=True)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: './fasthenry'
```

**Comment by vredzhepov** [comment]
I've faced the same issue. Have you managed to fix it?

**Comment by twitchyliquid64** [comment]
Unfortunately not :(
